/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gs.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PersonValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5288645863611902213L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonValue\",\"namespace\":\"gs.model\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\",\"doc\":\"Vorname\"},{\"name\":\"lastName\",\"type\":\"string\",\"doc\":\"Nachname\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PersonValue> ENCODER =
      new BinaryMessageEncoder<PersonValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PersonValue> DECODER =
      new BinaryMessageDecoder<PersonValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PersonValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PersonValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PersonValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PersonValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PersonValue from a ByteBuffer. */
  public static PersonValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Vorname */
  @Deprecated public java.lang.CharSequence firstName;
  /** Nachname */
  @Deprecated public java.lang.CharSequence lastName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PersonValue() {}

  /**
   * All-args constructor.
   * @param firstName Vorname
   * @param lastName Nachname
   */
  public PersonValue(java.lang.CharSequence firstName, java.lang.CharSequence lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return lastName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: lastName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return Vorname
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * Vorname
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return Nachname
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * Nachname
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Creates a new PersonValue RecordBuilder.
   * @return A new PersonValue RecordBuilder
   */
  public static gs.model.PersonValue.Builder newBuilder() {
    return new gs.model.PersonValue.Builder();
  }

  /**
   * Creates a new PersonValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PersonValue RecordBuilder
   */
  public static gs.model.PersonValue.Builder newBuilder(gs.model.PersonValue.Builder other) {
    return new gs.model.PersonValue.Builder(other);
  }

  /**
   * Creates a new PersonValue RecordBuilder by copying an existing PersonValue instance.
   * @param other The existing instance to copy.
   * @return A new PersonValue RecordBuilder
   */
  public static gs.model.PersonValue.Builder newBuilder(gs.model.PersonValue other) {
    return new gs.model.PersonValue.Builder(other);
  }

  /**
   * RecordBuilder for PersonValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonValue>
    implements org.apache.avro.data.RecordBuilder<PersonValue> {

    /** Vorname */
    private java.lang.CharSequence firstName;
    /** Nachname */
    private java.lang.CharSequence lastName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gs.model.PersonValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PersonValue instance
     * @param other The existing instance to copy.
     */
    private Builder(gs.model.PersonValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * Vorname
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }

    /**
      * Sets the value of the 'firstName' field.
      * Vorname
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public gs.model.PersonValue.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * Vorname
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * Vorname
      * @return This builder.
      */
    public gs.model.PersonValue.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * Nachname
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * Nachname
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public gs.model.PersonValue.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * Nachname
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * Nachname
      * @return This builder.
      */
    public gs.model.PersonValue.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PersonValue build() {
      try {
        PersonValue record = new PersonValue();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PersonValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<PersonValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PersonValue>
    READER$ = (org.apache.avro.io.DatumReader<PersonValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
